# Generated by Django 5.0.6 on 2026-08-04 22:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MonsterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('move', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fight', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('shoot', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('armour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('will', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('health', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('items', models.ManyToManyField(blank=True, related_name='monster_types', to='warbands.item')),
            ],
            options={
                'verbose_name_plural': 'Monster types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SoldierType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('move', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fight', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('shoot', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('armour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('will', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('health', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hire_cost', models.PositiveIntegerField(default=0, help_text='Gold crowns to hire.')),
                ('base_items', models.ManyToManyField(blank=True, related_name='soldier_types', to='warbands.item')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('xp_cost', models.PositiveIntegerField(default=0, help_text='Experience cost to learn this spell.')),
                ('base_casting_cost', models.PositiveSmallIntegerField(default=10, help_text='Admin-set base difficulty to cast this spell, before any school-alignment modifier.')),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spells', to='warbands.school')),
            ],
            options={
                'ordering': ['school__name', 'name'],
                'unique_together': {('name', 'school')},
            },
        ),
        migrations.CreateModel(
            name='MortalEnemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mortal Enemy', max_length=100)),
                ('type', models.CharField(default='humanoid', max_length=64)),
                ('current_health', models.SmallIntegerField(default=16)),
                ('move', models.PositiveSmallIntegerField(default=6)),
                ('fight', models.PositiveSmallIntegerField(default=2)),
                ('shoot', models.PositiveSmallIntegerField(default=0)),
                ('armour', models.PositiveSmallIntegerField(default=10)),
                ('will', models.PositiveSmallIntegerField(default=4)),
                ('health', models.PositiveSmallIntegerField(default=16)),
                ('items', models.ManyToManyField(blank=True, related_name='mortal_enemies', to='warbands.item')),
                ('out_of_game_primary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='warbands.spell')),
                ('out_of_game_secondary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='warbands.spell')),
                ('ranged_attack_primary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='warbands.spell')),
                ('ranged_attack_secondary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='warbands.spell')),
                ('utility_primary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='warbands.spell')),
                ('utility_secondary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='warbands.spell')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='grants_spell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granting_items', to='warbands.spell'),
        ),
        migrations.CreateModel(
            name='HomeBaseUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cost', models.PositiveIntegerField(default=0, help_text='Gold crowns to purchase this upgrade.')),
                ('troop_cost_modifier', models.IntegerField(default=0, help_text='Gold crowns added to (or, if negative, subtracted from) the hire cost of EVERY soldier type while this upgrade is owned. E.g. -10 for something like Carrier Pigeon.')),
                ('spell_cost_modifier', models.IntegerField(default=0, help_text='Casting cost added to (or, if negative, subtracted from) each spell in discounted_spells above, while this upgrade is owned.')),
                ('discounted_spells', models.ManyToManyField(blank=True, help_text='Specific spells whose casting cost is affected by spell_cost_modifier below, for any wizard who owns this upgrade and has learned that spell.', related_name='discounting_upgrades', to='warbands.spell')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Warband',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Warband', max_length=100)),
                ('mortal_enemy', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warband', to='warbands.mortalenemy')),
            ],
        ),
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, default=None, help_text='A short paragraph about this warband member, if any.', null=True)),
                ('current_health', models.SmallIntegerField(default=10)),
                ('price_paid', models.PositiveIntegerField(default=0, help_text='Gold crowns paid to hire this soldier (refunded in full when sold).')),
                ('move', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fight', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('shoot', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('armour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('will', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('health', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('items', models.ManyToManyField(blank=True, related_name='soldiers', to='warbands.item')),
                ('soldier_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='soldiers', to='warbands.soldiertype')),
                ('warband', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldiers', to='warbands.warband')),
            ],
        ),
        migrations.CreateModel(
            name='Wizard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Wizard', max_length=100)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('gold', models.PositiveIntegerField(default=400, help_text='Wizards start with 400gc.')),
                ('current_health', models.SmallIntegerField(default=16)),
                ('move', models.PositiveSmallIntegerField(default=6)),
                ('fight', models.PositiveSmallIntegerField(default=2)),
                ('shoot', models.PositiveSmallIntegerField(default=0)),
                ('armour', models.PositiveSmallIntegerField(default=10)),
                ('will', models.PositiveSmallIntegerField(default=4)),
                ('health', models.PositiveSmallIntegerField(default=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home_base_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wizards', to='warbands.homebasetype')),
                ('home_base_upgrades', models.ManyToManyField(blank=True, related_name='wizards', to='warbands.homebaseupgrade')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wizards', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, help_text='Chosen when the wizard is created. Determines the casting-cost modifier for spells outside this school.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wizards', to='warbands.school')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='warband',
            name='wizard',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warband', to='warbands.wizard'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('soldier', 'Soldier Hire'), ('home_base_upgrade', 'Home Base Upgrade')], max_length=32)),
                ('amount', models.PositiveIntegerField(help_text='Gold crowns spent.')),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('home_base_upgrade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_records', to='warbands.homebaseupgrade')),
                ('soldier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_record', to='warbands.soldier')),
                ('wizard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='warbands.wizard')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='mortalenemy',
            name='wizard',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mortal_enemy', to='warbands.wizard'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text="Optional label, e.g. 'The Frozen Vault'.", max_length=100)),
                ('treasures_earned', models.PositiveIntegerField(default=0)),
                ('gold_earned', models.PositiveIntegerField(default=0)),
                ('items_earned', models.TextField(blank=True, help_text='Items found from treasure this game.')),
                ('monsters_killed', models.PositiveIntegerField(default=0)),
                ('successful_spells', models.PositiveIntegerField(default=0)),
                ('unsuccessful_spells', models.PositiveIntegerField(default=0)),
                ('bonus_xp', models.PositiveIntegerField(default=0)),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wizard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='warbands.wizard')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Apprentice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Apprentice', max_length=100)),
                ('current_health', models.SmallIntegerField(default=14)),
                ('move', models.PositiveSmallIntegerField(default=6)),
                ('fight', models.PositiveSmallIntegerField(default=2)),
                ('shoot', models.PositiveSmallIntegerField(default=0)),
                ('armour', models.PositiveSmallIntegerField(default=10)),
                ('will', models.PositiveSmallIntegerField(default=2)),
                ('health', models.PositiveSmallIntegerField(default=14)),
                ('wizard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apprentice', to='warbands.wizard')),
            ],
        ),
        migrations.CreateModel(
            name='WizardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('location', models.CharField(choices=[('wizard', 'Carried by Wizard'), ('apprentice', 'Carried by Apprentice'), ('vault', 'Vault')], default='vault', max_length=16)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wizard_links', to='warbands.item')),
                ('wizard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wizard_items', to='warbands.wizard')),
            ],
        ),
        migrations.AddField(
            model_name='wizard',
            name='items',
            field=models.ManyToManyField(related_name='owned_by_wizards', through='warbands.WizardItem', to='warbands.item'),
        ),
        migrations.CreateModel(
            name='WizardSpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_invested', models.PositiveSmallIntegerField(default=0, help_text="Points spent lowering this spell's casting cost.")),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wizard_links', to='warbands.spell')),
                ('wizard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wizard_spells', to='warbands.wizard')),
            ],
        ),
        migrations.AddField(
            model_name='wizard',
            name='spells',
            field=models.ManyToManyField(related_name='known_by_wizards', through='warbands.WizardSpell', to='warbands.spell'),
        ),
        migrations.CreateModel(
            name='SchoolAffinity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField()),
                ('other_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affinities_reverse', to='warbands.school')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affinities', to='warbands.school')),
            ],
            options={
                'verbose_name_plural': 'School affinities',
                'unique_together': {('school', 'other_school')},
            },
        ),
        migrations.AddConstraint(
            model_name='warband',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('mortal_enemy__isnull', True), ('wizard__isnull', False)), models.Q(('mortal_enemy__isnull', False), ('wizard__isnull', True)), _connector='OR'), name='warband_belongs_to_exactly_one_owner'),
        ),
        migrations.AlterUniqueTogether(
            name='wizarditem',
            unique_together={('wizard', 'item', 'location')},
        ),
        migrations.AlterUniqueTogether(
            name='wizardspell',
            unique_together={('wizard', 'spell')},
        ),
    ]
