# Generated by Django 5.0.6 on 2026-08-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warbands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprentice',
            name='fight',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='apprentice',
            name='shoot',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apprentice',
            name='will',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='monstertype',
            name='fight',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monstertype',
            name='shoot',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monstertype',
            name='will',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mortalenemy',
            name='fight',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='mortalenemy',
            name='shoot',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mortalenemy',
            name='will',
            field=models.SmallIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='fight',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='shoot',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soldier',
            name='will',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soldiertype',
            name='fight',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soldiertype',
            name='shoot',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soldiertype',
            name='will',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wizard',
            name='fight',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='wizard',
            name='shoot',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wizard',
            name='will',
            field=models.SmallIntegerField(default=4),
        ),
    ]
