# Generated by Django 5.0.6 on 2026-09-07 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warbands', '0002_alter_apprentice_fight_alter_apprentice_shoot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-created_at']},
        ),
    ]
